on:
  push:
    branches:
      - main

name: Docs

jobs:
  docs:
    name: Build and deploy documentation
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
      - uses: taiki-e/install-action@f7e9f60cbb6fd0974db97e1044fe80439a7d98a5 # just
      - name: Build rustdoc
        run: just rustdoc
      - name: Organize
        run: |
          rm -rf target/gh-pages
          mkdir target/gh-pages
          mv target/doc/_redirects target/gh-pages
          mv target/doc target/gh-pages/rustdoc
      - name: Publish
        uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca # 1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: datatest-stable
          directory: target/gh-pages
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
